# Generated by Django 3.0.7 on 2020-06-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20200621_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_record',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient_record',
            name='check_out_period',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=64),
        ),
    ]
